<?php
  //Tracking code for the Intelligent Reach platform (http://www.intelligentreach.com).
  //Copyright © 2014 Intuitive Search Technologies Ltd.
  //Release under OSL license (http://opensource.org/licenses/osl-3.0).
  //
  //Product Page
?>
<?php 
$product = Mage::registry('current_product');
$store_id = Mage::app()->getstore()->getid();
$id = Mage::getModel('core/variable')->setStoreId($store_id)->loadByCode('intelligent_reach_id')->getValue();
?>
<script type="text/javascript">
  istCompanyId = "<?php echo $id ?>";
  istItem = "<?php echo $product->getId();?>";
</script>
<script type="text/javascript" src="//www.ist-track.com/ContainerItemJavaScript.ashx?id=<?php echo $id; ?>"></script>
