<?php
  //Tracking code for the Intelligent Reach platform (http://www.intelligentreach.com).
  //Copyright © 2014 Intuitive Search Technologies Ltd.
  //Release under OSL license (http://opensource.org/licenses/osl-3.0).
  //
  //Basket Page
?>
<?php
$store_id = Mage::app()->getstore()->getid();
$id = Mage::getModel('core/variable')->setStoreId($store_id)->loadByCode('intelligent_reach_id')->getValue();
?>
<?php $quote = Mage::getSingleton('checkout/session')->getQuote(); $cartItems = $quote->getAllItems(); $basketItems = "";?>
<?php foreach($cartItems as $item): ?> 
<?php if($item === end($cartItems)){$basketItems .= $item->getProductId(); }else{$basketItems .= $item->getProductId()."|";} ?> 
<?php endforeach ?>
<script type="text/javascript">
  istCompanyId = "<?php echo $id; ?>";
  istBasketItems = "<?php echo $basketItems; ?>";
</script>
<script type="text/javascript" src="//www.ist-track.com/ContainerBasketJavaScript.ashx?id=<?php echo $id; ?>"></script>
